### ISSUE TITLE
Support the `sass:meta` module

### ISSUE THREAD

**Issue by kaj** [kaj/rsass#129]
There should be complete support for the [`sass:meta`](https://sass-lang.com/documentation/modules/meta) module.  Some are done in #80, some improvements in #110, #113, and #126.

* [ ] `load-css` (I'm currently working on this)
* [x] `calc-args`
* [x] `calc-name`
* [x] `call`
* [x] `content-exists` (minor problems with error reporting remains)
* [x] `feature-exists` (the function is correct, but not all expected features are implemented)
* [x] `function-exists` (a problem with functions available from multiple global modules remains)
* [x] `get-function` (a problem with functions available from multiple global modules remains)
* [x] `global-variable-exists` (a problem with variables available from multiple global modules remains)
* [x] `inspect`
* [x] `keywords`
* [x] `mixin-exists`  (a problem with mixins available from multiple global modules remains)
* [x] `module-functions`
* [x] `module-variables`
* [ ] `type-of` (exists, but not yet correct for all arguments)
* [x] `variable-exists`  (a problem with functions available from multiple global modules remains)

Common problem:
* [ ] Handle things that exists globally from multiple modules.
